### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by brennanjl**
General cleanup, updating, and changes.

I have quite a few PRs open in `kwil-db`, so we will need to re-generate the reference docs once they get merged.

### CODE REVIEW

**Comment by brennanjl** [comment]
resolves https://github.com/kwilteam/docs/issues/138

**Comment by brennanjl** [comment]
resolves https://github.com/kwilteam/docs/issues/130

**Comment by brennanjl** [comment]
resolves https://github.com/kwilteam/docs/issues/128

**Review by KwilLuke — APPROVED** [review]
lgtm

**Pull request merged**
