### PR TITLE
regenerated docs, added json rpc

### PR DESCRIPTION
**Pull request by brennanjl**
Addressed the punchlist items found here: https://github.com/kwilteam/docs/issues/112

### CODE REVIEW

**Comment by brennanjl** [comment]
Added changes discussed here: https://github.com/kwilteam/kwil-db/pull/793#discussion_r1631569532

Charitha made the changes here: https://github.com/kwilteam/kwil-db/pull/801/commits/b189a03a5950c57bc9ef28f1ebf78ae8c6e43702

**Review by charithabandi — APPROVED** [review]

**Review by KwilLuke — APPROVED** [review]
lgtm - we should probably test the tutorials if you have not already.

**Comment by brennanjl** [comment]
I have not

**Comment by brennanjl** [comment]
will test now

**Pull request merged**
